on: 
  push:
    branch:
      - 'main'

name: CI eval prerelease macos

env:
  RUSTFLAGS: --cfg=web_sys_unstable_apis

jobs:
  
  macosbuild:
    name: Macos Build
    runs-on: macos-latest
    permissions: write-all
    strategy:
      fail-fast: false
    steps:
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Installing needed macos dependencies
        run: |
          brew update
          brew install jack

      - uses: actions/checkout@v2
        with:
            submodules: recursive


      - name: Cache rust compilations
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo
          
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
 
